### ISSUE TITLE
Add "cleaners"

### ISSUE THREAD

**Issue by jdugan6240** [jdugan6240/kak-bundle#11]
Some plugins, like kak-lsp, create artifacts outside of the plugin directory when installed. In addition to bundle-clean running a simple "rm -r" on the plugin directory, we should also allow the user to define "cleaners" for each plugin, or routines that are run in addition to the typical cleaning routine.

**Comment by rosingrind** [comment]
I have thoughts about this when I was tinkering with `kak-tree-sitter` too, and I have a question: is it possible to implement ergonomically inside `kak-bundle`, or maybe each plugin should ship a "cleaner" script? For example: `kak-lsp` may have `lsp.kak` and `cleanup.kak` files; if you call `bundle-clean` then `cleanup.kak` gets called before removing a plugin directory. What's your thoughts, may this approach have any value?

**Comment by jdugan6240** [comment]
Resolved by commit [7468da31e04d659b698ff5ac3454108113472457](https://github.com/jdugan6240/kak-bundle/commit/7468da31e04d659b698ff5ac3454108113472457)
