### ISSUE TITLE
Error: kak-bundle: can't declare highlighters for 'kak' filetype: 2:9: 'add-highlighter': duplicate id: 'bundle_keywords'

### ISSUE THREAD

**Issue by vbauerster** [jdugan6240/kak-bundle#14]
Whenever a file is opened with `edit` command, *debug* buffer is populated with:

```
Error: kak-bundle: can't declare highlighters for 'kak' filetype: 2:9: 'add-highlighter': duplicate id: 'bundle_keywords'
```

**Comment by jdugan6240** [comment]
Yep, this is due to the fact that we try to re-add the highlighters whenever we open a new kakscript file, even though they already exist. I'll fix that when I get home from work.

**Comment by jdugan6240** [comment]
OK, I just pushed a commit that **should** fix this. Please let me know if it works on your end.

**Comment by vbauerster** [comment]
Confirm it has been fixed. Thanks!
